source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!

def common
    pod 'WeexSDK', :git=>'git@github.com:apache/incubator-weex.git'
	pod 'WeexPluginLoader'#, '0.0.1.18'
    pod 'GCanvas', :path=>'../../../../../'
    pod 'SDWebImage', '3.7.5'
end

target 'WeexGcanvas' do
    common
end


