source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!

def common
    pod 'WeexPluginLoader', :git=>'git@github.com:kfeagle/WeexPluginLoader.git'
    pod 'GCanvas', :path=>'../../../../../'
    pod 'SDWebImage', '3.7.5'
    pod 'WeexSDK', '0.20.1'#, :git=>'git@github.com:apache/incubator-weex.git'
end

target 'WeexGcanvas' do
    common
end


