source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'GCanvasPlayground' do
  pod 'WXDevtool', :configurations => ['Debug']
  pod 'SocketRocket'
  pod 'ATSDK-Weex'
  pod 'WeexPluginLoader', :git=>'git@github.com:kfeagle/WeexPluginLoader.git'
  pod 'WeexSDK'#, '0.20.1'#, :git=>'git@github.com:apache/incubator-weex.git'

  #pod 'WeexGcanvas'
  pod 'WeexGcanvas', :path=>'../../../../../'
  pod 'GCanvas', :path=>'../../../../../'

end
