source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'GCanvasPlayground' do
  pod 'WXDevtool', :configurations => ['Debug']
  pod 'SocketRocket'
  pod 'ATSDK-Weex'
  
  #pod 'WeexGcanvas'
  pod 'WeexGcanvas', :path=>'../../../../../'
  pod 'GCanvas', :path=>'../../../../../'

end
